steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/marketplace/sistemasas:$SHORT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/marketplace/sistemasas:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - sistemasas
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/marketplace/sistemasas:$SHORT_SHA
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --update-env-vars=NODE_ENV=production,ROOT_DOMAIN=escovex.com,COOKIE_DOMAIN=.escovex.com,COOKIE_NAME=session,GCS_BUCKET_NAME=sistema_sas,GCP_PROJECT_ID=$PROJECT_ID
      - --quiet

options:
  logging: CLOUD_LOGGING_ONLY
